# V-Learning Platform Configuration
global:
  namespace: v-learning-test
  imageTag: main-6
  previousImageTag: main-5  # For canary deployments
  branch: main  # Options: dev, test, main

# Istio Service Mesh Configuration
# Note: Istio is now managed manually in the namespace
# This configuration is retained for reference only and has no effect
istio:
  enabled: true  # Set to true to enable Istio features
  # mTLS Configuration (simplified)
  mtls:
    enabled: false
    mode: PERMISSIVE  # PERMISSIVE allows both mTLS and plain traffic
  # Ingress Gateway Configuration (HTTP only)
  ingressGateway:
    enabled: true
    name: v-learning-gateway
    host: v-learning.local
    port: 80
  # Monitoring Configuration
  monitoring:
    serviceMonitor:
      enabled: false  # Set to true only if Prometheus Operator is installed
    prometheus:
      enabled: true  # Enable Prometheus scraping annotations on services
      path: "/internal/prometheus"  # Path for Prometheus metrics endpoint

# Canary Deployment Configuration (simplified)
canary:
  enabled: false
  # Traffic splitting - current vs previous image
  currentWeight: 90   # Traffic to current image tag
  previousWeight: 10  # Traffic to previous image tag
  # Which services to enable canary for
  userService: false
  courseService: false
  contentService: false
  enrollmentService: false
  certificateService: false

# Horizontal Pod Autoscaler Configuration
hpa:
  enabled: true
  # Default HPA settings for all microservices
  default:
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
    scaleDown:
      stabilizationWindowSeconds: 300
      percentValue: 10
      periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      percentValue: 50
      periodSeconds: 60
  # Per-service HPA overrides
  userService:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75
  courseService:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70
  contentService:
    enabled: true
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80
  enrollmentService:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 75
  certificateService:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80


# Resource requests and limits for microservices
resources:
  userService:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  courseService:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  contentService:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  enrollmentService:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  certificateService:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

# Database Configuration
postgres:
  enabled: false  # Disabled - not using PostgreSQL
  image: postgres:15-alpine
  database: pfe_learning
  username: pfe_user
  password: "123456"

# Service Discovery
eureka:
  enabled: true
  port: 8761

# API Gateway
gateway:
  enabled: true
  port: 8080
  nodePort: 30082

# Microservices
userService:
  enabled: true
  port: 8081

courseService:
  enabled: true
  port: 8082

contentService:
  enabled: true
  port: 8083

enrollmentService:
  enabled: true
  port: 8084

certificateService:
  enabled: true
  port: 8085

# Frontend
frontend:
  enabled: true
  port: 4200
  nodePort: 30420
