{{- if .Values.courseService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
        version: current
      # Note: Istio sidecar injection is now managed manually via namespace labels
      # or via istioctl commands
    spec:
      containers:
      - name: course-service
        image: mahdi0188/v-learning-course-service:{{ .Values.global.imageTag }}
        envFrom:
        - configMapRef:
            name: course-service-config
        ports:
        - containerPort: {{ .Values.courseService.port }}
        resources:
          requests:
            cpu: {{ .Values.resources.courseService.requests.cpu }}
            memory: {{ .Values.resources.courseService.requests.memory }}
          limits:
            cpu: {{ .Values.resources.courseService.limits.cpu }}
            memory: {{ .Values.resources.courseService.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: course-service
  ports:
  - port: {{ .Values.courseService.port }}
    targetPort: {{ .Values.courseService.port }}
  type: ClusterIP
{{- end }}
