{{- if .Values.contentService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
      - name: content-service
        image: {{ .Values.global.imageRegistry }}/v-learning-content-service:{{ .Values.global.imageTag }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:{{ .Values.eureka.port }}/eureka/"
        ports:
        - containerPort: {{ .Values.contentService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: content-service
  ports:
  - port: {{ .Values.contentService.port }}
    targetPort: {{ .Values.contentService.port }}
  type: ClusterIP
{{- end }}

---

{{- if .Values.enrollmentService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment-service
  template:
    metadata:
      labels:
        app: enrollment-service
    spec:
      containers:
      - name: enrollment-service
        image: {{ .Values.global.imageRegistry }}/v-learning-enrollment-service:{{ .Values.global.imageTag }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"  
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:{{ .Values.eureka.port }}/eureka/"
        ports:
        - containerPort: {{ .Values.enrollmentService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: enrollment-service
  ports:
  - port: {{ .Values.enrollmentService.port }}
    targetPort: {{ .Values.enrollmentService.port }}
  type: ClusterIP
{{- end }}

---

{{- if .Values.certificateService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificate-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certificate-service
  template:
    metadata:
      labels:
        app: certificate-service
    spec:
      containers:
      - name: certificate-service
        image: {{ .Values.global.imageRegistry }}/v-learning-certificate-service:{{ .Values.global.imageTag }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:{{ .Values.eureka.port }}/eureka/"
        ports:
        - containerPort: {{ .Values.certificateService.port }}
--- 
apiVersion: v1
kind: Service
metadata:
  name: certificate-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: certificate-service
  ports:
  - port: {{ .Values.certificateService.port }}
    targetPort: {{ .Values.certificateService.port }}
  type: ClusterIP
{{- end }}
