{{- if .Values.userService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: current
      # Note: Istio sidecar injection is now managed manually via namespace labels
      # or via istioctl commands
    spec:
      containers:
      - name: user-service
        image: mahdi0188/v-learning-user-service:{{ .Values.global.imageTag }}
        envFrom:
        - configMapRef:
            name: user-service-config
        ports:
        - containerPort: {{ .Values.userService.port }}
        resources:
          requests:
            cpu: {{ .Values.resources.userService.requests.cpu }}
            memory: {{ .Values.resources.userService.requests.memory }}
          limits:
            cpu: {{ .Values.resources.userService.limits.cpu }}
            memory: {{ .Values.resources.userService.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
  {{- if .Values.istio.monitoring.prometheus.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.userService.port }}"
    prometheus.io/path: "{{ .Values.istio.monitoring.prometheus.path }}"
  {{- end }}
spec:
  selector:
    app: user-service
  ports:
  - name: http
    port: {{ .Values.userService.port }}
    targetPort: {{ .Values.userService.port }}
  type: ClusterIP
{{- end }}
