{{- if .Values.eureka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: mahdi0188/v-learning-eureka-server:{{ .Values.global.imageTag }}
        envFrom:
        - configMapRef:
            name: eureka-config
        ports:
        - containerPort: {{ .Values.eureka.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: eureka-server
  ports:
  - name: http
    port: {{ .Values.eureka.port }}
    targetPort: {{ .Values.eureka.port }}
  type: ClusterIP
{{- end }}
