{{- if .Values.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: current
      # Note: Istio sidecar injection is now managed manually via namespace labels
      # or via istioctl commands
    spec:
      containers:
      - name: api-gateway
        image: mahdi0188/v-learning-api-gateway:{{ .Values.global.imageTag }}
        envFrom:
        - configMapRef:
            name: api-gateway-config
        ports:
        - containerPort: {{ .Values.gateway.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.global.namespace }}
  {{- if .Values.istio.monitoring.prometheus.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.gateway.port }}"
    prometheus.io/path: "{{ .Values.istio.monitoring.prometheus.path }}"
  {{- end }}
spec:
  selector:
    app: api-gateway
  ports:
  - port: {{ .Values.gateway.port }}
    targetPort: {{ .Values.gateway.port }}
    nodePort: {{ .Values.gateway.nodePort }}
  type: NodePort
{{- end }}
