{{- if eq (include "v-learning.istioEnabled" .) "true" }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: v-learning-vs
  namespace: {{ .Values.global.namespace }}
spec:
  hosts:
  - {{ .Values.istio.ingressGateway.host }}
  gateways:
  - {{ .Values.istio.ingressGateway.name }}
  http:
  # API routes to API Gateway
  - match:
    - uri:
        prefix: /api/
    route:
    - destination:
        host: api-gateway
        port:
          number: {{ .Values.gateway.port }}
    corsPolicy:
      allowCredentials: true
      allowHeaders:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Requested-With
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowOrigins:
      - exact: '*'
      maxAge: 24h
  # All other routes to Frontend
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend
        port:
          number: {{ .Values.frontend.port }}
    corsPolicy:
      allowCredentials: true
      allowHeaders:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Requested-With
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      allowOrigins:
      - exact: '*'
      maxAge: 24h
{{- end }}
